### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by Alex-Sour** [buidler-hub/rayli#12]
There are no examples anywhere of how the images look, not on producthunt, not on NPM, not even here.

Add Images To The README and producthunt page please.

**Comment by Kira272921** [comment]
Hey! Sorry for the inconvenience. Here is a demo of how the images look:

Theme: Falcon
<img width="520" alt="Example demo of Rayli" src="https://user-images.githubusercontent.com/90365542/168532175-32c808ba-1710-414d-bf81-c3d34ec24868.png">

Theme: Candy
<img width="520" alt="Example demo of Rayli" src="https://user-images.githubusercontent.com/90365542/168532488-20bd5b57-29f4-4793-8ee9-654b894d02f7.png">
